name: FTP Upload

on:
  push:
    branches: [ main ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: FTP site
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.cluster021.hosting.ovh.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: www/
          git-ftp-args: --insecure --all